<a href="https://colab.research.google.com/github/sangram-jr/Deep-Learning/blob/main/Next-word-prediction/Next_Word_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [7]:
df = pd.read_csv("qoute_dataset.csv")

In [8]:
df.head()

                                               quote           Author
0  “The world as we have created it is a process ...  Albert Einstein
1  “It is our choices, Harry, that show what we t...     J.K. Rowling
2  “There are only two ways to live your life. On...  Albert Einstein
3  “The person, be it gentleman or lady, who has ...      Jane Austen
4  “Imperfection is beauty, madness is genius and...   Marilyn Monroe

In [9]:
df.shape

(3038, 2)

In [10]:
quotes = df['quote']
quotes.head()

0    “The world as we have created it is a process ...
1    “It is our choices, Harry, that show what we t...
2    “There are only two ways to live your life. On...
3    “The person, be it gentleman or lady, who has ...
4    “Imperfection is beauty, madness is genius and...
Name: quote, dtype: object

In [11]:

# convert all to lower case
quotes = quotes.str.lower()

# remove punctuation
import string
translator = str.maketrans('', '', string.punctuation)
quotes = quotes.apply(lambda x: x.translate(translator))

In [12]:
quotes.head()

0    “the world as we have created it is a process ...
1    “it is our choices harry that show what we tru...
2    “there are only two ways to live your life one...
3    “the person be it gentleman or lady who has no...
4    “imperfection is beauty madness is genius and ...
Name: quote, dtype: object

# Tokenization

In [13]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [14]:
vocab_size = 10000

tokinizer = Tokenizer(num_words=vocab_size)
tokinizer.fit_on_texts(quotes)


sequence = tokinizer.texts_to_sequences(quotes)

In [15]:


for i in range(3):
  print(quotes[i])

“the world as we have created it is a process of our thinking it cannot be changed without changing our thinking”
“it is our choices harry that show what we truly are far more than our abilities”
“there are only two ways to live your life one is as though nothing is a miracle the other is as though everything is a miracle”

In [16]:
for i in range(3):
  print(sequence[i])

[713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12, 809, 104, 752, 70, 2461]
[947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52, 54, 70, 3676]
[1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5, 1157, 1, 101, 7, 29, 329, 126, 7, 5, 3677]

set input and output

In [17]:
#One sentence
#     ↓
#[Word1, Word2, Word3, Word4]
#     ↓     X                    y
#     ├── [Word1]              → Word2
#     ├── [Word1, Word2]       → Word3
#     └── [Word1, Word2, Word3] → Word4

X = []
y = []

for seq in sequence:
  for i in range(1,len(seq)):
    input_seq = seq[:i]
    output_seq = seq[i]
    X.append(input_seq)
    y.append(output_seq)

In [18]:
max_len = max(len(x) for x in X)
print(max_len)

745

add padding to input

In [19]:
# make all your input sequences the same length
from tensorflow.keras.preprocessing.sequence import pad_sequences
X_padded = pad_sequences(X, maxlen=max_len, padding='pre')

In [20]:
y = np.array(y)

In [21]:
X_padded.shape

(85271, 745)

In [22]:
#Each target word will be represented using a vector of 2,000 positions using one hot encoding

from tensorflow.keras.utils import to_categorical
y_one_hot = to_categorical(y, num_classes=vocab_size)

In [23]:
y.shape

(85271,)

In [24]:
y_one_hot.shape

(85271, 10000)

# simple RNN model

In [25]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,SimpleRNN,LSTM, Dense



embedding_dim = 50
rnn_units = 128 ##RNN will maintain a hidden state of size:

rnn_model = Sequential()

#add embedding to rnn_model
rnn_model.add(
    Embedding(
        input_dim=vocab_size, #The model has a vocabulary of up to 2,000 word IDs.
        output_dim=embedding_dim, #Each word is converted into a 16-dimensional vector.
        input_length=max_len
    )
)

#Add SimpleRNN
rnn_model.add(SimpleRNN(units=rnn_units))
#output layer(creates 2,000 output neurons)
rnn_model.add(Dense(units=vocab_size, activation='softmax')) #Softmax converts the 2,000 outputs into probabilities.

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [26]:
rnn_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [27]:
rnn_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

# LSTM model

In [28]:
lstm_model = Sequential()

lstm_model.add(
    Embedding(
        input_dim=vocab_size,
        output_dim=embedding_dim,
        input_length=max_len
       )
)

lstm_model.add(LSTM(units=rnn_units))
lstm_model.add(Dense(units=vocab_size, activation='softmax'))

In [29]:


lstm_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [30]:
lstm_model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

# Train the LSTM model

In [36]:
epochs=100
batch_size=128

In [37]:
history_lstm=lstm_model.fit(
    X_padded,
    y_one_hot,
    epochs=epochs,
    batch_size=batch_size,
    validation_split=0.1
)

Epoch 1/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.1640 - loss: 4.6345 - val_accuracy: 0.1163 - val_loss: 6.7472
Epoch 2/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.1710 - loss: 4.5053 - val_accuracy: 0.1160 - val_loss: 6.8384
Epoch 3/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.1804 - loss: 4.3854 - val_accuracy: 0.1161 - val_loss: 6.9407
Epoch 4/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.1930 - loss: 4.2680 - val_accuracy: 0.1155 - val_loss: 7.0232
Epoch 5/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.2057 - loss: 4.1560 - val_accuracy: 0.1125 - val_loss: 7.1112
Epoch 6/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.2204 - loss: 4.0495 - val_accuracy: 0.1136 - val_loss: 7.2012
Epoch 7/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.2354 - loss: 3.9484 - val_accuracy: 0.1152 - val_loss: 7.2743
Epoch 8/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.2490 - loss: 3.8545 - val_accuracy: 0.1125 - val_loss: 7.3523
Epoch 9/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.2615 - loss: 3.7661 - val_accuracy: 0.1137 - val_loss: 7.4416
Epoch 10/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.2734 - loss: 3.6822 - val_accuracy: 0.1115 - val_loss: 7.5249
Epoch 11/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.2859 - loss: 3.6050 - val_accuracy: 0.1078 - val_loss: 7.6069
Epoch 12/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.2971 - loss: 3.5307 - val_accuracy: 0.1099 - val_loss: 7.6673
Epoch 13/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.3092 - loss: 3.4600 - val_accuracy: 0.1094 - val_loss: 7.7332
Epoch 14/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.3178 - loss: 3.3938 - val_accuracy: 0.1067 - val_loss: 7.8077
Epoch 15/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.3286 - loss: 3.3291 - val_accuracy: 0.1086 - val_loss: 7.8683
Epoch 16/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.3382 - loss: 3.2672 - val_accuracy: 0.1041 - val_loss: 7.9415
Epoch 17/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.3468 - loss: 3.2078 - val_accuracy: 0.1025 - val_loss: 8.0035
Epoch 18/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.3565 - loss: 3.1519 - val_accuracy: 0.1066 - val_loss: 8.0590
Epoch 19/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.3662 - loss: 3.0958 - val_accuracy: 0.1045 - val_loss: 8.1323
Epoch 20/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.3747 - loss: 3.0423 - val_accuracy: 0.0992 - val_loss: 8.1925
Epoch 21/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 56ms/step - accuracy: 0.3833 - loss: 2.9903 - val_accuracy: 0.1008 - val_loss: 8.2610
Epoch 22/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.3904 - loss: 2.9407 - val_accuracy: 0.1010 - val_loss: 8.3321
Epoch 23/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.3990 - loss: 2.8918 - val_accuracy: 0.0997 - val_loss: 8.3787
Epoch 24/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4077 - loss: 2.8437 - val_accuracy: 0.1030 - val_loss: 8.4466
Epoch 25/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4160 - loss: 2.7996 - val_accuracy: 0.1010 - val_loss: 8.5061
Epoch 26/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4231 - loss: 2.7539 - val_accuracy: 0.0996 - val_loss: 8.5631
Epoch 27/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4312 - loss: 2.7107 - val_accuracy: 0.0983 - val_loss: 8.6224
Epoch 28/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4386 - loss: 2.6677 - val_accuracy: 0.0965 - val_loss: 8.6799
Epoch 29/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.4464 - loss: 2.6271 - val_accuracy: 0.0964 - val_loss: 8.7407
Epoch 30/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.4533 - loss: 2.5870 - val_accuracy: 0.0960 - val_loss: 8.8073
Epoch 31/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4586 - loss: 2.5483 - val_accuracy: 0.0942 - val_loss: 8.8460
Epoch 32/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 42s 56ms/step - accuracy: 0.4675 - loss: 2.5113 - val_accuracy: 0.0938 - val_loss: 8.9116
Epoch 33/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.4738 - loss: 2.4731 - val_accuracy: 0.0942 - val_loss: 8.9772
Epoch 34/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.4813 - loss: 2.4375 - val_accuracy: 0.0936 - val_loss: 9.0407
Epoch 35/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.4872 - loss: 2.4022 - val_accuracy: 0.0955 - val_loss: 9.0984
Epoch 36/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.4944 - loss: 2.3690 - val_accuracy: 0.0953 - val_loss: 9.1540
Epoch 37/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.4996 - loss: 2.3354 - val_accuracy: 0.0909 - val_loss: 9.2030
Epoch 38/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.5072 - loss: 2.3030 - val_accuracy: 0.0926 - val_loss: 9.2707
Epoch 39/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 56ms/step - accuracy: 0.5126 - loss: 2.2711 - val_accuracy: 0.0906 - val_loss: 9.3192
Epoch 40/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.5191 - loss: 2.2389 - val_accuracy: 0.0898 - val_loss: 9.3735
Epoch 41/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5229 - loss: 2.2087 - val_accuracy: 0.0916 - val_loss: 9.4385
Epoch 42/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.5302 - loss: 2.1781 - val_accuracy: 0.0918 - val_loss: 9.4876
Epoch 43/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.5358 - loss: 2.1497 - val_accuracy: 0.0896 - val_loss: 9.5300
Epoch 44/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5415 - loss: 2.1212 - val_accuracy: 0.0915 - val_loss: 9.5954
Epoch 45/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.5465 - loss: 2.0964 - val_accuracy: 0.0890 - val_loss: 9.6470
Epoch 46/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.5520 - loss: 2.0674 - val_accuracy: 0.0883 - val_loss: 9.6876
Epoch 47/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 56ms/step - accuracy: 0.5578 - loss: 2.0398 - val_accuracy: 0.0878 - val_loss: 9.7390
Epoch 48/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.5619 - loss: 2.0141 - val_accuracy: 0.0894 - val_loss: 9.8036
Epoch 49/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 56ms/step - accuracy: 0.5680 - loss: 1.9886 - val_accuracy: 0.0870 - val_loss: 9.8759
Epoch 50/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.5724 - loss: 1.9653 - val_accuracy: 0.0886 - val_loss: 9.9155
Epoch 51/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5772 - loss: 1.9397 - val_accuracy: 0.0854 - val_loss: 9.9818
Epoch 52/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.5824 - loss: 1.9156 - val_accuracy: 0.0872 - val_loss: 9.9986
Epoch 53/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.5879 - loss: 1.8914 - val_accuracy: 0.0863 - val_loss: 10.0541
Epoch 54/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.5914 - loss: 1.8691 - val_accuracy: 0.0856 - val_loss: 10.1086
Epoch 55/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.5970 - loss: 1.8465 - val_accuracy: 0.0877 - val_loss: 10.1632
Epoch 56/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.6004 - loss: 1.8242 - val_accuracy: 0.0864 - val_loss: 10.2085
Epoch 57/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.6057 - loss: 1.8034 - val_accuracy: 0.0836 - val_loss: 10.2437
Epoch 58/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.6103 - loss: 1.7825 - val_accuracy: 0.0837 - val_loss: 10.2941
Epoch 59/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.6145 - loss: 1.7615 - val_accuracy: 0.0845 - val_loss: 10.3457
Epoch 60/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.6182 - loss: 1.7411 - val_accuracy: 0.0849 - val_loss: 10.3894
Epoch 61/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.6224 - loss: 1.7215 - val_accuracy: 0.0836 - val_loss: 10.4670
Epoch 62/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.6258 - loss: 1.7018 - val_accuracy: 0.0830 - val_loss: 10.5164
Epoch 63/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6302 - loss: 1.6833 - val_accuracy: 0.0838 - val_loss: 10.5588
Epoch 64/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.6341 - loss: 1.6648 - val_accuracy: 0.0823 - val_loss: 10.6103
Epoch 65/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.6391 - loss: 1.6438 - val_accuracy: 0.0844 - val_loss: 10.6579
Epoch 66/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.6422 - loss: 1.6284 - val_accuracy: 0.0802 - val_loss: 10.6957
Epoch 67/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.6456 - loss: 1.6111 - val_accuracy: 0.0829 - val_loss: 10.7462
Epoch 68/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.6498 - loss: 1.5934 - val_accuracy: 0.0828 - val_loss: 10.7963
Epoch 69/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.6527 - loss: 1.5762 - val_accuracy: 0.0829 - val_loss: 10.8412
Epoch 70/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.6567 - loss: 1.5578 - val_accuracy: 0.0781 - val_loss: 10.8798
Epoch 71/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.6599 - loss: 1.5429 - val_accuracy: 0.0824 - val_loss: 10.9249
Epoch 72/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.6630 - loss: 1.5269 - val_accuracy: 0.0826 - val_loss: 10.9637
Epoch 73/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.6662 - loss: 1.5109 - val_accuracy: 0.0787 - val_loss: 11.0197
Epoch 74/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.6698 - loss: 1.4961 - val_accuracy: 0.0777 - val_loss: 11.0496
Epoch 75/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.6718 - loss: 1.4822 - val_accuracy: 0.0793 - val_loss: 11.0955
Epoch 76/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.6766 - loss: 1.4630 - val_accuracy: 0.0811 - val_loss: 11.1441
Epoch 77/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.6799 - loss: 1.4494 - val_accuracy: 0.0796 - val_loss: 11.1917
Epoch 78/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.6827 - loss: 1.4352 - val_accuracy: 0.0814 - val_loss: 11.2254
Epoch 79/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.6853 - loss: 1.4209 - val_accuracy: 0.0780 - val_loss: 11.2800
Epoch 80/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.6895 - loss: 1.4088 - val_accuracy: 0.0826 - val_loss: 11.3190
Epoch 81/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 57ms/step - accuracy: 0.6925 - loss: 1.3922 - val_accuracy: 0.0800 - val_loss: 11.3817
Epoch 82/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.6946 - loss: 1.3784 - val_accuracy: 0.0815 - val_loss: 11.4267
Epoch 83/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.6973 - loss: 1.3660 - val_accuracy: 0.0787 - val_loss: 11.4674
Epoch 84/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.6997 - loss: 1.3543 - val_accuracy: 0.0800 - val_loss: 11.5121
Epoch 85/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.7025 - loss: 1.3402 - val_accuracy: 0.0768 - val_loss: 11.5414
Epoch 86/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 57ms/step - accuracy: 0.7061 - loss: 1.3274 - val_accuracy: 0.0763 - val_loss: 11.5984
Epoch 87/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.7100 - loss: 1.3139 - val_accuracy: 0.0775 - val_loss: 11.6468
Epoch 88/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.7108 - loss: 1.3003 - val_accuracy: 0.0763 - val_loss: 11.6989
Epoch 89/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.7133 - loss: 1.2883 - val_accuracy: 0.0770 - val_loss: 11.7366
Epoch 90/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.7155 - loss: 1.2792 - val_accuracy: 0.0760 - val_loss: 11.7738
Epoch 91/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.7188 - loss: 1.2661 - val_accuracy: 0.0759 - val_loss: 11.8172
Epoch 92/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.7223 - loss: 1.2531 - val_accuracy: 0.0767 - val_loss: 11.8734
Epoch 93/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.7236 - loss: 1.2423 - val_accuracy: 0.0774 - val_loss: 11.9074
Epoch 94/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 57ms/step - accuracy: 0.7265 - loss: 1.2328 - val_accuracy: 0.0761 - val_loss: 11.9554
Epoch 95/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 57ms/step - accuracy: 0.7287 - loss: 1.2214 - val_accuracy: 0.0762 - val_loss: 12.0007
Epoch 96/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 56ms/step - accuracy: 0.7302 - loss: 1.2101 - val_accuracy: 0.0768 - val_loss: 12.0292
Epoch 97/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 35s 58ms/step - accuracy: 0.7335 - loss: 1.1995 - val_accuracy: 0.0742 - val_loss: 12.0820
Epoch 98/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 56ms/step - accuracy: 0.7367 - loss: 1.1878 - val_accuracy: 0.0766 - val_loss: 12.1121
Epoch 99/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.7386 - loss: 1.1787 - val_accuracy: 0.0728 - val_loss: 12.1617
Epoch 100/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.7409 - loss: 1.1695 - val_accuracy: 0.0770 - val_loss: 12.2142

In [39]:
from tensorflow.keras.models import load_model

lstm_model = load_model("lstm_model.h5")

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [40]:
lstm_model.save('lstm_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

# prediction

In [43]:
#It converts: (word → number) into (number → word)

index_to_word = {}
for word, index in tokinizer.word_index.items():
  index_to_word[index] = word

In [44]:
def predictor(model,tokenizer,text,max_len):
  #Convert text to lowercase
  text = text.lower()
  # Convert text into word IDs
  seq = tokenizer.texts_to_sequences([text])[0]
  # add padding into text because model expects every input to have the same length.
  seq = pad_sequences([seq], maxlen=max_len, padding='pre')
  # Make prediction
  pred = model.predict(seq,verbose = 0)
  #Find the highest-probability word
  #np.argmax() finds the position/index of the largest value.
  pred_index = np.argmax(pred)
  return index_to_word[pred_index]

In [45]:
seed_text = "what are you"
next_word = predictor(lstm_model,tokinizer,seed_text,max_len)
print(next_word)

implying

In [64]:
#It predicts one word at a time, adds that word to the predictor fucntion, then uses the new sentence to predict the next word.
def generate_text(model,tokenizer,seed_text,max_len,n_words): #n_words => Number of new words to generate
  for _ in range(n_words):
    next_word = predictor(model,tokenizer,seed_text,max_len)
    if next_word == "":
      break
    seed_text += " " + next_word
  return seed_text

In [65]:
seed = "i love"
generate_text = generate_text(lstm_model,tokinizer,seed,max_len,5)
print(generate_text)

i love you in this way because

download tokenizer,max_len,index_to_word

In [66]:
import pickle

#Save tokenizer
with open("tokenizer.pkl", "wb") as f:
  pickle.dump(tokinizer, f)

#Save max_len
with open("max_len.pkl", "wb") as f:
  pickle.dump(max_len, f)

#Save index → word mapping
with open("index_to_word.pkl", "wb") as f:
  pickle.dump(index_to_word, f)